name: Execute SSH Commands

on:
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: "30 0,13 * * *"  # 每天 北京时间 早0点30分 晚13点30分 各运行一次

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSHPass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Get ACCOUNTSSSH_JSON
        id: get-accountsssh
        run: |
          echo "$ACCOUNTSSSh_JSON" > accountsssh.json
        env:
          ACCOUNTSSSH_JSON: ${{ secrets.ACCOUNTSSSH_JSON }}
        # 从 GitHub Secrets 获取 ACCOUNTSSSH_JSON 变量，并保存到文件 accountsssh.json

      - name: Generate SSH Commands
        id: generate-ssh-commands
        run: |
          echo "#!/bin/bash" > sshpass.sh
          while IFS= read -r account; do
            username=$(echo "$account" | jq -r '.username')
            password=$(echo "$account" | jq -r '.password')
            ssh=$(echo "$account" | jq -r '.ssh')

            echo "echo \"Executing for $username@$ssh\"" >> sshpass.sh
            echo "sshpass -p '$password' ssh -o StrictHostKeyChecking=no '$username@$ssh' 'bash <(curl -s https://raw.githubusercontent.com/amosgansweet/sev00-RecoveryCommand-WebLogin/main/check_cron.sh)'" >> sshpass.sh
          done < <(jq -c '.[]' accountsssh.json)
          chmod +x sshpass.sh

      - name: Execute SSH Commands
        run: ./sshpass.sh
